# KalKalori — Heat Exchanger Open Engine
# GNU GPL v3 only

"""Stable warning codes for ``core.phase_change`` (v0.6.1).

These are plain string codes, consistent with the rest of KalKalori
(``core.common.warnings.ModelWarning.code`` is a free-form string; there is
no shared enum of warning codes elsewhere in the codebase). Centralizing
them here avoids typos scattering slightly different strings for the same
condition across ``core.phase_change`` modules.
"""

from __future__ import annotations

OUTSIDE_CONDENSATION_DETECTED = "OUTSIDE_CONDENSATION_DETECTED"
INSIDE_CONDENSATION_DETECTED = "INSIDE_CONDENSATION_DETECTED"
PHASE_CHANGE_NEAR_ONSET = "PHASE_CHANGE_NEAR_ONSET"
PHASE_CHANGE_DISABLED_BUT_POSSIBLE = "PHASE_CHANGE_DISABLED_BUT_POSSIBLE"
INSIDE_CONDENSATION_NOT_SUPPORTED = "INSIDE_CONDENSATION_NOT_SUPPORTED"
PURE_WATER_STEAM_CONDENSATION_NOT_SUPPORTED = "PURE_WATER_STEAM_CONDENSATION_NOT_SUPPORTED"
MULTIPLE_PHASE_CHANGE_SIDES_NOT_SUPPORTED = "MULTIPLE_PHASE_CHANGE_SIDES_NOT_SUPPORTED"
FROSTING_NOT_SUPPORTED = "FROSTING_NOT_SUPPORTED"
LEWIS_NUMBER_ASSUMED = "LEWIS_NUMBER_ASSUMED"
FULLY_DRAINED_CONDENSATE_ASSUMED = "FULLY_DRAINED_CONDENSATE_ASSUMED"
CONDENSATE_FILM_RESISTANCE_NOT_MODELLED = "CONDENSATE_FILM_RESISTANCE_NOT_MODELLED"
CONDENSATE_FILM_HYDRAULICS_NOT_MODELLED = "CONDENSATE_FILM_HYDRAULICS_NOT_MODELLED"
CONDENSATE_STATE_INCONSISTENT = "CONDENSATE_STATE_INCONSISTENT"
REENTRAINMENT_NOT_MODELLED = "REENTRAINMENT_NOT_MODELLED"
OUTSIDE_CONDENSATION_NOT_CONVERGED = "OUTSIDE_CONDENSATION_NOT_CONVERGED"
INSIDE_CONDENSATION_NOT_CONVERGED = "INSIDE_CONDENSATION_NOT_CONVERGED"
WET_SURFACE_FRACTION_0D_ESTIMATE = "WET_SURFACE_FRACTION_0D_ESTIMATE"
EFFECTIVE_CAPACITY_RATE_0D_APPROXIMATION = "EFFECTIVE_CAPACITY_RATE_0D_APPROXIMATION"
EFFECTIVE_OUTSIDE_ALPHA_LIMITED = "EFFECTIVE_OUTSIDE_ALPHA_LIMITED"
EFFECTIVE_INSIDE_ALPHA_LIMITED = "EFFECTIVE_INSIDE_ALPHA_LIMITED"

# v0.6.2 -- pure water/steam condensation inside tubes.
TWO_PHASE_PRESSURE_DROP_NOT_SUPPORTED = "TWO_PHASE_PRESSURE_DROP_NOT_SUPPORTED"
PURE_STEAM_ZONE_COUPLING_NOT_CONVERGED = "PURE_STEAM_ZONE_COUPLING_NOT_CONVERGED"
PHASE_CHANGE_DISABLED_BUT_REQUIRED = "PHASE_CHANGE_DISABLED_BUT_REQUIRED"
PURE_STEAM_CONDENSATION_OUTSIDE_NOT_SUPPORTED = "PURE_STEAM_CONDENSATION_OUTSIDE_NOT_SUPPORTED"
